### ISSUE TITLE
Project: HTML best practices

### ISSUE THREAD

**Issue by estelle** [openwebdocs/project#115]
All HTML examples should follow best practices.

Media
* [x] All images should include an `alt` attribute
   * [x] Create spreadsheet of missing alt attributes
* [ ] All images should aslo include a `height` and `width` (newer best practice)
* [ ] All audio files should have a transcript, captions, and description
* [ ] All video files should have a transcript
* [ ] Video and audio should have autoplay=off (not sure this is necessary anymore)

Form elements
* [x] No form control should exist without an associated label
  * [x] checkbox
  * [x] radio
  * [x] hidden
  * [ ] text
  * [x] password
  * [x] tel
  * [ ] number
  * [ ] color
  * [ ] range
  * [ ] date/time
  * [ ] select
  * [ ] textarea

* [ ] Every form control should have an `id` (except in the rare case where implicit labels are used)  
  * [x] checkbox
  * [x] radio
  * [ ] text
  * [x] password
  * [ ] tel
  * [ ] number
  * [ ] color
  * [ ] range
  * [ ] date/time
  * [ ] select
  * [ ] textarea

* [ ] All `input` elements should include a `name` (and value if needed)
  * [x] checkbox (value recommended)
  * [x] radio (value required)
  * [x] hidden (value required)
  * [ ] text
  * [x] password
  * [ ] tel
  * [ ] number
  * [ ] color
  * [ ] range
  * [ ] date/time
  * [ ] select
  * [ ] textarea

* [x] All checkboxes, radio buttons, and hidden input types should also include a `value`
   * [ ] checkboxes and radio buttons should be inside `<fieldset>`s
   * [ ] 
* [x] HTML docs should be standards compliant
  * [x] doctype
  * [x] `html` element should include a `lang` attribute.
  * [x] `charset`
  * [X] `title`
  * [X] `viewport` meta
* [x] Type attribute is NOT needed
  * [x] script
  * [x] stylesheet

Required attributes, elements, and content

* [x] Ensure `abbr` has a `title` attribute unless the abbreviation is preceded or followed by the definition.
* [ ] Ensure all links have adequate content ("click here" is a no-no).
* [ ] Every `<table>` should have a table `<caption>`
   * [ ] in code examples
   * [ ] in markdown (how is this done?)

Deprecated content

* [x] #139
* [X] Ensure `acronym` is no longer used.
* [x] Figure out if `hgroup` is back. If no, remove it from all but the essential occurrences

**Comment by Seirdy** [comment]
> Figure out if `hgroup` is back. If no, remove it from all but the essential occurrences

`hgroup` does seem to be back; a change to the HTML Living Standard now clarifies that it can define a subtitle.

See https://github.com/whatwg/html/pull/7829

**Comment by Rumyra** [comment]
@estelle the HTML guidelines are here https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/HTML if you wanted to update to reflect your changes above 👍

**Comment by nschonni** [comment]
> * All images should include an `alt` attribute

I turned back on the MD045 rule to see how many were left, since I think there has already been a bunch of cleanup

```
files/en-us/learn/common_questions/what_are_browser_developer_tools/index.md:145 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/forms/advanced_form_styling/index.md:153 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/forms/advanced_form_styling/index.md:154 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/forms/advanced_form_styling/index.md:155 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/forms/advanced_form_styling/index.md:156 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/forms/advanced_form_styling/index.md:157 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/forms/advanced_form_styling/index.md:158 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/getting_started_with_the_web/publishing_your_website/index.md:73 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/html/introduction_to_html/getting_started/index.md:65 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/html/tables/structuring_planet_data/index.md:66 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/javascript/client-side_web_apis/manipulating_documents/index.md:47 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/javascript/client-side_web_apis/manipulating_documents/index.md:79 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/javascript/client-side_web_apis/manipulating_documents/index.md:267 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/javascript/client-side_web_apis/third_party_apis/index.md:196 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/javascript/client-side_web_apis/third_party_apis/index.md:390 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/javascript/first_steps/silly_story_generator/index.md:62 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/javascript/first_steps/variables/index.md:99 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/javascript/first_steps/what_went_wrong/index.md:64 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/javascript/first_steps/what_went_wrong/index.md:87 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/javascript/first_steps/what_went_wrong/index.md:114 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/javascript/objects/adding_bouncing_balls_features/index.md:59 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/javascript/objects/json/index.md:198 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/javascript/objects/object_building_practice/index.md:50 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/performance/measuring_performance/index.md:90 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/performance/measuring_performance/index.md:94 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/server-side/express_nodejs/forms/delete_author_form/index.md:178 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/server-side/express_nodejs/forms/delete_author_form/index.md:188 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/server-side/express_nodejs/forms/delete_author_form/index.md:193 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/server-side/express_nodejs/forms/update_book_form/index.md:216 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/server-side/express_nodejs/routes/index.md:54 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/accessibility/index.md:129 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/accessibility/index.md:223 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/accessibility/index.md:306 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/accessibility/index.md:334 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/automated_testing/index.md:325 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/automated_testing/index.md:405 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/automated_testing/index.md:407 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/automated_testing/index.md:492 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/automated_testing/index.md:496 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/automated_testing/index.md:504 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/automated_testing/index.md:710 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/javascript/index.md:87 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/javascript/index.md:101 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/javascript/index.md:115 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/javascript/index.md:194 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/javascript/index.md:204 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/javascript/index.md:347 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md:124 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md:153 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md:235 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md:247 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.md:253 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/your_own_automation_environment/index.md:602 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/your_own_automation_environment/index.md:666 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/your_own_automation_environment/index.md:728 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/learn/tools_and_testing/cross_browser_testing/your_own_automation_environment/index.md:796 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/add_a_button_to_the_toolbar/index.md:53 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/add_a_button_to_the_toolbar/index.md:57 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/anatomy_of_a_webextension/index.md:28 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/contextualidentities/index.md:16 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/devtools/panels/elementspanel/createsidebarpane/index.md:25 MD045/no-alt-text Images should have alternate text (alt text)        
files/en-us/mozilla/add-ons/webextensions/api/devtools/panels/extensionsidebarpane/index.md:20 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/find/find/index.md:96 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/find/find/index.md:98 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/find/find/index.md:227 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/menus/index.md:43 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/menus/index.md:49 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/menus/index.md:53 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/menus/index.md:59 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/notifications/index.md:20 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/pageaction/index.md:19 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/pkcs11/index.md:30 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/pkcs11/index.md:32 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/proxy/register/index.md:20 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/proxy/unregister/index.md:19 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/userscripts/working_with_userscripts/index.md:45 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/userscripts/working_with_userscripts/index.md:106 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/webnavigation/index.md:23 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/api/webrequest/index.md:21 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/browser_actions/index.md:11 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/extending_the_developer_tools/index.md:123 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/native_messaging/index.md:21 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/user_interface/browser_action/index.md:10 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/user_interface/context_menu_items/index.md:17 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/user_interface/notifications/index.md:11 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/user_interface/page_actions/index.md:14 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/user_interface/popups/index.md:14 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/user_interface/sidebars/index.md:15 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/what_are_webextensions/index.md:16 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/what_are_webextensions/index.md:22 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/what_are_webextensions/index.md:28 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/what_are_webextensions/index.md:34 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/what_are_webextensions/index.md:44 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/your_second_webextension/index.md:29 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/your_second_webextension/index.md:401 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/your_second_webextension/index.md:403 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/add-ons/webextensions/your_second_webextension/index.md:405 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/mozilla/firefox/releases/3.5/icc_color_correction_in_firefox/index.md:15 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/canvas_api/tutorial/drawing_shapes/index.md:22 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/canvas_api/tutorial/drawing_shapes/index.md:305 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/canvas_api/tutorial/transformations/index.md:85 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/canvas_api/tutorial/transformations/index.md:127 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/canvas_api/tutorial/using_images/index.md:206 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/canvasrenderingcontext2d/clip/index.md:25 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/canvasrenderingcontext2d/createlineargradient/index.md:21 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/canvasrenderingcontext2d/linejoin/index.md:34 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/canvasrenderingcontext2d/rotate/index.md:25 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/canvasrenderingcontext2d/translate/index.md:29 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/channel_messaging_api/using_channel_messaging/index.md:40 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/channelmergernode/index.md:18 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/channelsplitternode/index.md:20 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/console/index.md:165 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/console/index.md:235 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/console/index.md:259 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/console/table/index.md:42 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/console/table/index.md:57 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/console/timeend/index.md:54 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/console/timelog/index.md:76 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/css_object_model/determining_the_dimensions_of_elements/index.md:24 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/css_object_model/determining_the_dimensions_of_elements/index.md:30 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/document_object_model/traversing_an_html_table_with_javascript_and_dom_interfaces/index.md:140 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/document_object_model/traversing_an_html_table_with_javascript_and_dom_interfaces/index.md:197 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/document_object_model/traversing_an_html_table_with_javascript_and_dom_interfaces/index.md:225 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/document_object_model/traversing_an_html_table_with_javascript_and_dom_interfaces/index.md:238 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/document_object_model/traversing_an_html_table_with_javascript_and_dom_interfaces/index.md:256 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/document_object_model/traversing_an_html_table_with_javascript_and_dom_interfaces/index.md:264 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/document_object_model/using_the_w3c_dom_level_1_core/index.md:31 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/document_object_model/whitespace/index.md:269 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/element/clientheight/index.md:36 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/element/clientwidth/index.md:33 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/element/getboundingclientrect/index.md:53 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/element/mouseenter_event/index.md:100 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/element/mouseenter_event/index.md:105 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/element/mouseleave_event/index.md:96 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/element/mouseleave_event/index.md:102 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/element/scrollheight/index.md:19 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/htmlelement/offsetheight/index.md:39 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/htmlelement/offsetleft/index.md:39 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/htmlelement/offsetwidth/index.md:37 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/navigator/registerprotocolhandler/web-based_protocol_handlers/index.md:40 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/notifications_api/index.md:32 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/notifications_api/using_the_notifications_api/index.md:21 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/presentation_api/index.md:17 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/service_worker_api/using_service_workers/index.md:42 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/service_worker_api/using_service_workers/index.md:52 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/service_worker_api/using_service_workers/index.md:108 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/service_worker_api/using_service_workers/index.md:161 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/stereopannernode/index.md:20 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/streams_api/concepts/index.md:25 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/streams_api/concepts/index.md:47 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/streams_api/index.md:30 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/textdecoder/index.md:24 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/web_audio_api/basic_concepts_behind_web_audio_api/index.md:390 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/web_audio_api/basic_concepts_behind_web_audio_api/index.md:394 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/web_storage_api/using_the_web_storage_api/index.md:103 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/web_storage_api/using_the_web_storage_api/index.md:107 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/webgl_api/matrix_math_for_the_web/index.md:275 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/webvr_api/using_the_webvr_api/index.md:41 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/webvr_api/using_the_webvr_api/index.md:237 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/webxr_device_api/fundamentals/index.md:51 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/window/personalbar/index.md:26 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/window/statusbar/index.md:52 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/xrwebgllayer/getnativeframebufferscalefactor/index.md:100 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/api/xrwebgllayer/getnativeframebufferscalefactor/index.md:146 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/guide/css/getting_started/challenge_solutions/index.md:231 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/guide/mobile/separate_sites/index.md:24 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/guide/user_input_methods/index.md:21 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/compression/index.md:38 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/compression/index.md:44 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/compression/index.md:54 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/compression/index.md:58 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/connection_management_in_http_1.x/index.md:78 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/content_negotiation/index.md:20 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/content_negotiation/index.md:33 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/content_negotiation/index.md:106 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/cors/index.md:26 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/cors/index.md:110 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/cors/index.md:173 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/cors/index.md:306 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/http/redirections/index.md:24 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/javascript/guide/introduction/index.md:92 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/javascript/reference/global_objects/math/index.md:139 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/javascript/reference/global_objects/promise/index.md:35 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/mathml/element/menclose/index.md:40 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/mathml/element/mmultiscripts/index.md:42 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/mathml/element/mmultiscripts/index.md:67 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/mathml/element/mtable/index.md:57 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/media/formats/video_codecs/index.md:399 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/media/formats/video_codecs/index.md:415 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/performance/animation_performance_and_frame_rate/index.md:25 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/privacy/firefox_tracking_protection/index.md:30 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/privacy/firefox_tracking_protection/index.md:34 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/progressive_web_apps/add_to_home_screen/index.md:57 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/progressive_web_apps/add_to_home_screen/index.md:207 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/progressive_web_apps/add_to_home_screen/index.md:211 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/fills_and_strokes/index.md:33 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/fills_and_strokes/index.md:56 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/fills_and_strokes/index.md:76 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/paths/index.md:37 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/paths/index.md:72 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/paths/index.md:160 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/paths/index.md:198 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/paths/index.md:265 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/patterns/index.md:76 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/web/svg/tutorial/positions/index.md:22 MD045/no-alt-text Images should have alternate text (alt text)
files/en-us/webassembly/concepts/index.md:99 MD045/no-alt-text Images should have alternate text (alt text)
```

**Comment by teoli2003** [comment]
It will be very interesting to turn this rule on once done. That way, no PR could be merged with a missing alt attribute. That won't guarantee the quality of the attribute's value, but at least its existence.

**Comment by teoli2003** [comment]
> Are you interested in PRs for
> 
>     * fix single quotes in html to double quotes
> 
These will be fixed automatically by Prettier (soon I hope), so that's not useful (as we will have to run Prettier anyway)

>     * add missing lang attribute in html element

I would gladly review such PRs (with 50-100 entries each)

**Comment by Elchi3** [comment]
Thanks for filing this OWD project proposal!

Can we clarify the scope here?

Is this about updating https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Writing_style_guide/Code_style_guide/HTML ?

Or about fixing all of MDN with regards to these best practices? (seems to large for a single project)

Or is the idea to invest into tooling to make sure HTML best practices are enforced? If so, is there a plan for this work?

**Comment by Elchi3** [comment]
In yesterday's planning call we agreed that there are too many things at once in this project proposal.

It would be good to:
- Finish the `alt` attribute project (maybe still have a new project on this one, so we make sure we go to end for all missing `alt` attributes)
- Maybe choose a second HTML best practice from the list and do a community outreach again so we crowd source fixing it , again. (from the list above, choose something important and crowd source-able).

Assigning @estelle to prepare these two new HTML best practice project proposals.

**Comment by CBID2** [comment]
Is this issue still open?

**Comment by Elchi3** [comment]
@estelle Is there still work left here?

**Comment by estelle** [comment]
Yes, Only the checked topics are done. The ones without checkmarks have not been confirmed. 

On the last task: I do not know how to include a caption on tables in markdown.

**Comment by CBID2** [comment]
> Yes, Only the checked topics are done. The ones without checkmarks have not been confirmed.
> 
> On the last task: I do not know how to include a caption on tables in markdown.

I’ll try it @estelle

**Comment by CBID2** [comment]
> > Yes, Only the checked topics are done. The ones without checkmarks have not been confirmed.
> > On the last task: I do not know how to include a caption on tables in markdown.
> 
> I’ll try it @estelle

Hey @estelle, can you provide me the link to the file we're changing?

**Comment by estelle** [comment]
It's all of MDN, starting with [`content/tree/main/files/en-us/web`](https://github.com/mdn/content/tree/main/files/en-us/web)

It's a large job, but manageable in pieces. I recommend picking one sub-task, such as `type="number"` in `Every form control should have an id ` doing a search for `type="number"`, then, if there are at least 5 edits, submitting a PR for that subtask. 

It is best, when starting out, to do smallish PRs. But, you don't want to do a PR for every change either, because then it takes longer to do the "admin" for the PR then actually editing the code. It's a balance.  For example, if there are more that 20 files edited, perhaps do a PR for the CSS directory and another for the HTML directory.

Hope that helps, and thank you for helping!

**Comment by CBID2** [comment]
> It's all of MDN, starting with [`content/tree/main/files/en-us/web`](https://github.com/mdn/content/tree/main/files/en-us/web)
> 
> It's a large job, but manageable in pieces. I recommend picking one sub-task, such as `type="number"` in `Every form control should have an id ` doing a search for `type="number"`, then, if there are at least 5 edits, submitting a PR for that subtask.
> 
> It is best, when starting out, to do smallish PRs. But, you don't want to do a PR for every change either, because then it takes longer to do the "admin" for the PR then actually editing the code. It's a balance. For example, if there are more that 20 files edited, perhaps do a PR for the CSS directory and another for the HTML directory.
> 
> Hope that helps, and thank you for helping!

Hi @estelle! Here's [my PR](https://github.com/mdn/content/pull/25187)for the caption issue. I only did one for now. Let me know if I'm one the right track. 😄

**Comment by CBID2** [comment]
> content/tree/main/files/en-us/web

Hi @estelle! 😄 I found an area to add a caption element. Here's the[PR](https://github.com/mdn/content/pull/25399) for it. I had writer's block in coming up with an intriguing title, so feel free to revise it.

**Comment by CBID2** [comment]
I think I made an error in this [PR](https://github.com/mdn/content/pull/25400). I'm not quite sure what "Markdownlint (PR files)" means. Can someone help?

**Comment by CBID2** [comment]
I need assistance with this [PR](https://github.com/mdn/content/pull/25613)

**Comment by teoli2003** [comment]
I think this has been automatically closed as #25612 had "Resolved #115" in it (It should have been something like "Part of #115" as it is not actually solving all of it. Reopening.

**Comment by CBID2** [comment]
> I think this has been automatically closed as #25612 had "Resolved #115" in it (It should have been something like "Part of #115" as it is not actually solving all of it. Reopening.

Made [the change](https://github.com/mdn/content/pull/25612) @teoli2003

**Comment by CBID2** [comment]
Hey @estelle. I've noticed that only 29 of the 63 tasks are completed, so I think it would be best to reopen this issue.
