### ISSUE TITLE
OWD Project: Document the Web Share Target API

### ISSUE THREAD

**Issue by tomayac** [openwebdocs/project#126]
### Problem statement

https://w3c.github.io/web-share-target/ needs documentation

It’s supported by Chromium on Android and Edge on Windows. 

CC: @robnyman 

### Proposed solutions

See task list.

### Task list

- [ ] Create a new page https://developer.mozilla.org/en-US/docs/Web/Manifest/share_target
- [ ] Possibly update https://github.com/mdn/browser-compat-data/blob/main/html/manifest/share_target.json 
- [ ] Update https://developer.mozilla.org/en-US/docs/Web/API/Web_Share_API to at least reference the share_target manifest member.
- [ ] ... possibly more

### Priority assessment

- **Effort**: Small. One new manifest member.
- **Dependencies**: None.
- **Community enablement**: None.
- **Momentum**:  Filed twice with MDN already (see below). Seems like there is demand.
- **Enabling learners**: n/a
- **Enabling professionals**: n/a
- **Underrepresented topics / Ethical web**:  n/a
- **Operational necessities**: no.
- **Addressing needs of the web industry**: Closes another gap so that web apps behave like native apps.

### More information

Filed with MDN before:
- https://github.com/mdn/content/issues/8887
- https://github.com/mdn/content/issues/10291

**Comment by Elchi3** [comment]
Thanks for your proposal! Looks good to me.
I've updated the request a bit to fill in more info for us.

**Comment by Elchi3** [comment]
I've sent two PRs to fix this.

https://github.com/mdn/content/pull/20930
https://github.com/mdn/browser-compat-data/pull/17848
