### ISSUE TITLE
2022 Q4 Projects

### ISSUE THREAD

**Issue by Elchi3** [openwebdocs/project#131]
## Q4 projects

This list contains the projects we already agreed to work on in Q4. Agreed Q4 projects are labeled with https://github.com/openwebdocs/project/labels/q4%202022.

- [ ] https://github.com/openwebdocs/project/issues/89

## Proposals

This list contains the projects we are considering to work on in Q4. We are still determining their priority and the OWD Steering Committee will hand in their votes in early October. You can still file new proposals here: https://github.com/openwebdocs/project/issues/new?assignees=&labels=not+ready&template=owd-project.yml

Votable proposals are labeled with https://github.com/openwebdocs/project/labels/ready.
- [ ] https://github.com/openwebdocs/project/issues/27
- [ ] https://github.com/openwebdocs/project/issues/43
- [ ] https://github.com/openwebdocs/project/issues/62
- [ ] https://github.com/openwebdocs/project/issues/81
- [ ] https://github.com/openwebdocs/project/issues/85
- [ ] https://github.com/openwebdocs/project/issues/92
- [ ] https://github.com/openwebdocs/project/issues/111
- [ ] https://github.com/openwebdocs/project/issues/127
- [ ] https://github.com/openwebdocs/project/issues/129
- [ ] https://github.com/openwebdocs/project/issues/130

## Tabled

Issues that need more information or aren't ready yet are not considered for Q4. They are labeled https://github.com/openwebdocs/project/labels/not%20ready. Please take a look at the issues and provide more information if necessary.

**Comment by Elchi3** [comment]
Please hand in your votes to me. Which are your top 3 projects from the above list under "Proposals"?

**Comment by wbamberg** [comment]
See also: https://github.com/web-platform-tests/interop/milestone/2?closed=1

**Comment by Elchi3** [comment]
Amount of people who voted so far: 5 
(happy to take more votes until next Wednesday)

| Project | Votes |  
|---|---|
|  #27    |  +   | 
|  #43    |  ++   | 
|  #62    |  +++   | 
|  #81    |  +   |
|  #85    |  +   |
|  #104    |  +   |  
|  #92    |  +++   |
|  #137    |  +   |
|  #138    |  ++   |

**Comment by sideshowbarker** [comment]
I vote for #104 and can commit to putting a significant amount of time into helping with work on it

**Comment by Elchi3** [comment]
Q4 is over. Q1 planning is in https://github.com/openwebdocs/project/issues/151
