### ISSUE TITLE
Subtask: Remaining missing `alt` text

### ISSUE THREAD

**Issue by estelle** [openwebdocs/project#133]
### Problem statement

There are still 153 missing alt attributes. 
[Missing alt and surrounding text](https://github.com/openwebdocs/project/files/9650142/missing_alt.txt)
[Spreadsheet with link and image URL](https://docs.google.com/spreadsheets/d/1cDHee6mwDMlY6zANEmg8MjR8tL-wrCS86uawpWZ4XbA/edit#gid=0)

### Proposed solutions

Get volunteers to add `alt` attributes
Address the ones volunteers don't address

### Task list

- [x] Create a list & Spreadsheet.
- [x] Create an issue on MDN
- [x] Recruit volunteers to address the issue
- [x] Address images not addressed by volunteers
- [x] Review PRs
- [ ] Maintain/Update the spreadsheet
- [x] Smile!
