### ISSUE TITLE
HTML Attributes: Boolean and Enumerated

### ISSUE THREAD

**Issue by estelle** [openwebdocs/project#136]
### Problem statement

The work "enumerated" is used multiple times on MDN, and virtually no one knows what it means, especially since the term as used in the spec (values defined individually) differs from the common definition of 'counted'.

### Proposed solutions

It would be good to have a page of attributes listing boolean, enumerated, text, numeric, and other.

We don't have attribute pages for all attributes, but for those we do have, we should also add the tag "boolean" and "enumerated" to all relevant pages, so we can automate later on that each enumerated attribute has a values section.

### Task list

HTML Attributes
  - [ ] Page of all attributes
      - [ ] enumerated
      - [ ] boolean
      - [ ] text
      - [ ] numeric
      - [ ] other

Glossary and linking terms
  - [X] Glossary page for Boolean (already existed)
    - [X] Link "Boolean" to that glossary term
  - [X] Add glossary page for enumerated
    - [X] Link "enumerated" to that glossary term

Removed suggestion: ~~add tags to all attribute pages~~

**Comment by wbamberg** [comment]
We talked about this in the content planning meeting and thought:

First, it would be helpful to split this project up:
- as a first step we should have documentation of the different attribute types, especially boolean and enumerated attributes
- next we could ensure that in the intro to pages like https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable, where we say "The _thing_ global attribute is an enumerated attribute", we link "enumerated" to that documentation.

We could have a project just for this piece for now?

Second, we would prefer not to represent attribute type using tags: if we wanted to do this we could have a metadata item for it perhaps.

**Comment by estelle** [comment]
I created an enumerated glossary term and linked many (not all) instances of enumerated to the glossary term. I only linked when the term meant "limited list of values". I did not link when it meant "counted" as that is a non-normative definition not defined in the glossary term.
