### ISSUE TITLE
Documentation needed for Interop 2022

### ISSUE THREAD

**Issue by estelle** [openwebdocs/project#137]
### Problem statement

Keep track that everything in Interop 2022 is documented.

### Task list
Legend:
- [x] Documented
- [ ] Missing
- [ ] **NR** Not implemented: not ready to be documented (?) 

**Note:** Entries match the [15 areas of focus](https://web.dev/interop-2022/#the-15-areas-of-focus).

TODO: Check that we have documentation for all of these. Create issues if we don't. Create a master issue for the missing documentation:

#### 2022 Focus Areas:

- [x] _Cascade layers_ (openwebdocs/project/issues/94)
- [ ] _Color spaces and CSS color functions_ (openwebdocs/project/issues/92)
     - [x] [`color-mix()`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-mix) 
     - [ ] **NR** [`color-contrast()`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/color-contrast)
     - [ ] Guides and refactor
- [x] **NR** New _viewport units_:  `lv*`, `sv*`, and `dv*`.
    - Needs to be documented on [length](https://developer.mozilla.org/en-US/docs/Web/CSS/length) page
- [x] _Scrolling_  - needs a learn / guide
     - [x] [scroll snap](https://developer.mozilla.org/docs/Web/CSS/CSS_Scroll_Snap) - needs better content
         - Should BCD for all properties be added to this overview page?
     - [x] [scroll-behavior](https://developer.mozilla.org/docs/Web/CSS/scroll-behavior)
     - [x] [overscroll-behavior](https://developer.mozilla.org/docs/Web/CSS/overscroll-behavior)
     - [x] Other properties: See [scroll snap feature proposals](https://github.com/argyleink/ScrollSnapExplainers)
     - [x] Named Scrolled Progress Timelines (https://github.com/mdn/content/issues/21069)
       - [x] `scroll-timeline-*` (https://github.com/mdn/content/pull/21277)
     - [x] #141
- [ ] _Subgrid_ 
    - [x] [subgrid](https://developer.mozilla.org/docs/Web/CSS/CSS_Grid_Layout/Subgrid) 
    - [x] [`grid-template-columns`](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns) 
    - [x] [`grid-template-rows`](https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-rows)
    - [ ] **?** display: grid applied
- [x] _Containment_ (the `contain` property) (mdn/content/issues/20876)
   - [X] [CSS Containment](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Containment)
- [x] _Dialog windows with HTML_ 
   - [x] The [`<dialog>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) element
   - [x] `inert` global attribute (See this [blog post](https://developer.chrome.com/articles/inert/))
       - [x] add the explanation to the [`dialog`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) page.
       - [x] add the attribute to the [global attributes page](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes) (already in spec and bcd on that page)
       - [X] HTMLElement.inert
   - [x] `::backdrop` pseudo
   - [x] `open` attribute
   - [x] remove polyfill from dialog page.
- [x] _Form controls_
    - [x] CSS [`appearance`](https://developer.mozilla.org/en-US/docs/Web/CSS/appearance)
    - [x] CSS [`accent-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color)
    - [x] [`input type=week`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/week)
    - [x] [`input type=month`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/month)
    - [ ] **?** Infinite backtracking
    - [x] `files` attribute [`input type=file`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file)
    - [x] `rel` attribute on [`form`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form) element
- [x] _Typography and Encodings_ 
    - [x] [`font-variant-alternates`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-alternates)
    - [x] [`font-variant-position`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-position)
    - [x] the `ic` unit
    - [ ] **?** CJK text encodings
 - [x] _Web compat_ (no action on docs, beside bcd)

#### 2021 Focus areas
 - [x] _Aspect ratio_
   - [x] [Guide page](https://developer.mozilla.org/en-US/docs/Web/Media/images/aspect_ratio_mapping)
   - [x] CSS [`aspect-ratio`](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio)
   - [x] Media query: [`@media/aspect-ratio`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/aspect-ratio) 
   - [x] #143
 - [x] [_Flexbox_](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout)
 - [x] [_Grid_](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout)
 - [x] _Sticky positioning_
   - [x] [`position:sticky`](https://developer.mozilla.org/en-US/docs/Web/CSS/position#sticky)
   - [ ] Should we have more, a guide?
 - [x] _Transforms_
   - [X] [`translate`](https://developer.mozilla.org/en-US/docs/Web/CSS/translate)
   - [X] [`scale`](https://developer.mozilla.org/en-US/docs/Web/CSS/scale)
   - [X] [`rotate`](https://developer.mozilla.org/en-US/docs/Web/CSS/rotate)
   - [x] [`transform`](https://developer.mozilla.org/en-US/docs/Web/CSS/transform) 
   - [x] #140

**Comment by wbamberg** [comment]
See also: https://github.com/web-platform-tests/interop/milestone/2?closed=1
