### ISSUE TITLE
OWD Proposal: revamp Form Validation documentation

### ISSUE THREAD

**Issue by teoli2003** [openwebdocs/project#138]
### Problem statement

MDN documents form validation at several places (Web/API, Web/API/Constraint_Validation, Learn Area, Web/Guide), incompletely, and with poor navigation (missing sidebars).

This is a fundamental API in Web development, quite stable.

We need a clear, complete and navigable documentation.

### Proposed solutions

Let's add the missing reference page, move the guide under Constraint Validation, and eventually split it in several pages. Review the content of the Learning Area.

### Task list

- [ ] Add missing Constraint Validation API reference pages (like `checkValidity()`)) for each HTML*Element that can be validated
- [ ] Move the guide page under the overview page for Constraint Validation API page
- [ ] Create a sidebar to ease navigation
- [ ] Review/Correct and extend the guide page
- [ ] Review the overview page
- [ ] Review the section under LA about Constraint Validation
- [ ] Make sure these pages can be found (it is unlikely that people type "Constraint Validation" in a search engine; let's do some SEO here!

### Priority assessment

- **Effort**: 
  This is about 10-15 reference pages, and max 3 guide pages.
- **Dependencies**: 
  None
- **Community enablement**: 
  None
- **Momentum**: 
  None
- **Enabling learners**: 
  Yes, this is a fundamental skill to master to create a website
- **Enabling professionals**:
  Professionals tend to overuse JS for this
- **Underrepresented topics / Ethical web**:
  None 
- **Operational necessities**:
  Missing sidebars must be fixed anyway, currently the guide is not in the bad structure.
- **Addressing needs of the web industry**:

**Comment by shamankayka** [comment]
``
