### ISSUE TITLE
OWD Project: Convert Yari to full ESM

### ISSUE THREAD

**Issue by queengooborg** [openwebdocs/project#145]
### Problem statement

Currently, Yari is still primarily written with CommonJS rather than ESM (although some parts use ESM already).  This means that Yari cannot update dependencies that have switched to pure ESM, which leads to potential security risks and the inability to use new features.  To ensure that Yari can upgrade to newer dependencies easily, we should tackle this sooner rather than later.

### Proposed solutions

The only solution applicable is to work on migrating Yari over to ESM.  This will take a significant amount of work, but it is most certainly essential work.

### Task list

- [x] Convert CJS imports to ESM imports
- [x] Fix all imports
- [x] Replace use of `__dirname` and `__filename` as they are unavailable in ESM
- [x] Fix mocking of modules in unit tests
- [x] Catch and fix any and all bugs, issues, etc. during conversion

### Priority assessment

- **Effort**: ~~Significant; Yari contains a LOT of source code~~ None any longer; project is actually almost complete!
- **Dependencies**: None known
- **Community enablement**: Promotes future community enablement (since PR work is already done); helps reduce confusion since some parts are CJS and others are ESM
- **Momentum**: There is significant interest, including from Yari engineers
- **Enabling learners**: N/A
- **Enabling professionals**: N/A
- **Underrepresented topics / Ethical web**: N/A
- **Operational necessities**: Yes; explained above
- **Addressing needs of the web industry**: N/A

### More information

At the time of opening this project, it has actually mostly been completed (see https://github.com/mdn/yari/pull/7623).  The reason for opening this issue is to mark it as another completed project on OWD's agenda.

**Comment by queengooborg** [comment]
This has now been finished!
