### ISSUE TITLE
2023 H1 Projects

### ISSUE THREAD

**Issue by Elchi3** [openwebdocs/project#151]
## H1 projects

This list contains the projects we agreed to work on in the first half (H1) of 2023. Agreed H1 projects are labeled with https://github.com/openwebdocs/project/labels/H1%202023.

### Almost finished

- [ ] https://github.com/openwebdocs/project/issues/91 (Will + Jean-Yves)

### Continue in H2

- [ ] https://github.com/openwebdocs/project/issues/147 (Estelle + Dipika)
- [ ] https://github.com/openwebdocs/project/issues/153 

### Done

- [x] https://github.com/mdn/mdn/issues/284 (Will)
- [x] https://github.com/openwebdocs/project/issues/152 (Jean-Yves + Florian)
- [x] https://github.com/openwebdocs/project/issues/62 (Florian + Will)
- [x] https://github.com/openwebdocs/project/issues/85  (Vinyl + Florian)
- [x] https://github.com/openwebdocs/project/issues/104 (Will + Florian + Jean-Yves)
- [x] https://github.com/mdn/mdn/issues/280 (Patrick + Will + Estelle)

---

There are more project proposals filed with us and on the shared roadmap with the Mozilla team. We will get to them in in a future quarter.

Query list for more projects: 
- https://github.com/openwebdocs/project/labels/ready
- https://github.com/openwebdocs/project/labels/not%20ready

**Comment by Elchi3** [comment]
> The PWA documentation project mentions "+ someone to help drive and review it". Any idea who that will be 😉 ?

Updated :) Both Will and Estelle like to help.

**Comment by Elchi3** [comment]
Hi all, H1 is over. Here are the documentation projects Open Web Docs was able to complete (besides daily reviewing, and content maintenance work, of course):

- Will Bamberg [retitled Web/API pages](https://github.com/mdn/mdn/issues/284).
- Jean-Yves Perrier [document missing API pages supported by 3 engines ](https://github.com/openwebdocs/project/issues/152)(part 1 of a larger project).
- Estelle Weyl, Patrick Brosset and Will Bamberg [revamped the Progressive Web Apps documentation](https://github.com/mdn/mdn/issues/280).
- Florian Scholz [updated MDN Performance API docs](https://github.com/openwebdocs/project/issues/62).
- Vinyl Da.i'gyu-Kazotetsu and Florian Scholz [fixed errors in BCD for API, CSS and JS going back to at least 2020](https://github.com/openwebdocs/project/issues/85).
- Vinyl Da.i'gyu-Kazotetsu released several new versions of the bcd-collector project. See https://mdn-bcd-collector.gooborg.com/changelog
- Will Bamberg and Florian Scholz [worked on supporting same name for static method and instance method](https://github.com/openwebdocs/project/issues/104)
- (almost finished) Jean-Yves Perrier and Will Bamberg [finalized the page types project](https://github.com/openwebdocs/project/issues/91).
- (to be continued in H2) Estelle Weyl [worked on the giant list of CSS specification module landing pages](https://github.com/openwebdocs/project/issues/147)

Thanks to everyone who helped us achieve these things and to all the reviewers of the PRs we submitted. Also, thanks to the individual donors and to our sponsoring companies for making this work possible.

H2 planning has started. Last week, the OWD staff team has already talked to OWD platinum sponsors and GC members about potential H2 projects. The list of projects is also available publicly on our project repo. [Link](https://github.com/openwebdocs/project/issues?q=is%3Aissue+is%3Aopen+label%3A%22H2+2023+proposals%22). As said in the last SC call, please join us on July 12 in the OWD content planning call to finalize H2 planning. You (yes, you, as in every SC member!) can still submit new project ideas using our [issue template](https://github.com/openwebdocs/project/issues/new/choose). Thanks!

I'm closing this issue. There will be a new H2 tracking issue soon.
