### ISSUE TITLE
OWD project: Doc structures for WebIDL concepts

### ISSUE THREAD

**Issue by Elchi3** [openwebdocs/project#159]
### Problem statement

In MDN Web API reference docs, we've been using [WebIDL](https://webidl.spec.whatwg.org/) to derive rules for how we want to structure and make the API docs most consistent and useful for web developers.

For example, we said:
- Interfaces always get a page and Interface members are subpages.
- We avoid documenting mixins or dictionaries
- Static API members get the `_static` suffix in the MDN page slug and in BCD paths.
- etc.

For certain WebIDL concepts, or annotations, we are less clear how to consistently document things. For example,
- Maplikes and setlikes 
- stringifiers, jsonifiers
- (... and more)

### Proposed solutions

Provide MDN authors (and readers) a clear structure for Web API docs by agreeing on how and where to document aspects of Web APIs like maplikes, jsonifiers, (async) iterables etc.

Ideal outcome: Any WebIDL fragment can be taken and it is clear what it will mean in terms of structure and docs on MDN and in BCD. This will make the docs predictable and also it will be easier to generate docs from tooling with consistent structures.

### Task list

- [x] Investigate and list which sort of WebIDL concepts exist (use webref or similar)
- [ ] For each WebIDL concept, determine if we have agreement how to document it on MDN and how we record it in BCD.
- [ ] For each unclear concept, start a discussion and come to a rule.
- [ ] Update MDN and BCD per the new rules
- [ ] Update MDN meta docs
- [ ] Find a place for where WebIDL concepts are explained to web developers (consensus seems to not do this in the glossary)

A good starting point is https://github.com/mdn/browser-compat-data/issues/6367

### Priority assessment

- **Effort**: Unclear, initial research needed.
- **Dependencies**: 
- **Community enablement**: Discussion will be in the open. Feedback will be welcome.
- **Momentum**:
- **Enabling learners**:  
- **Enabling professionals**:
- **Underrepresented topics / Ethical web**: 
- **Operational necessities**:
- **Addressing needs of the web industry**:

### More information

Open Web Docs (OWD) is a non-profit collective funded by corporate and individual donations.

In order for this project to happen, please consider donating to OWD on https://opencollective.com/open-web-docs.
For more information on sponsorship and membership tiers, see https://openwebdocs.org/membership/

More information is available at https://openwebdocs.org/.
For questions, please reach out to [florian@openwebdocs.org](mailto:florian@openwebdocs.org).

**Comment by Josh-Cena** [comment]
See also https://github.com/mdn/content/issues/7844

**Comment by teoli2003** [comment]
I used WebRef to start building a list of concepts to document, that is, concepts actually in use. Some will lead to significant work; others should be reasonably quick to deal with.

### Extended attributes (This list is a WIP)

- [ ] `[AllowShared]` [WebIDL spec, §3.3.2](https://webidl.spec.whatwg.org/#AllowShare) 
- [ ] `[Clamp]` [WebIDL spec, §3.3.3](https://webidl.spec.whatwg.org/#Clamp)   Related to `[EnforceRange]`
- [ ] `[CrossOriginIsolated]` [WebIDL spec, §3.3.4](https://webidl.spec.whatwg.org/#CrossOriginIsolated)
- [ ] `[Default]` [WebIDL spec, §3.3.5](https://webidl.spec.whatwg.org/#Default) Only for `toJSON()` for now.
- [ ] `[EnforceRange]` [WebIDL spec, §3.3.6](https://webidl.spec.whatwg.org/#EnforceRange) Related to `[Clamp]`
- [ ] `[Exposed=…]` [WebIDL spec, §3.3.7](https://webidl.spec.whatwg.org/#Exposed) With `[Global]` and maybe `[SecureContext]`, part of a realm initiative?
- [ ] `[Global]` [WebIDL spec, §3.3.8](https://webidl.spec.whatwg.org/#Global ) With `[Exposed]` and maybe `[SecureContext]`, part of a realm initiative?
- [ ] `[NewObject]` [WebIDL spec, §3.3.9](https://webidl.spec.whatwg.org/#NewObject) Very common, related to `[SameObject]`
- [ ] `[PutForwards=…]` [WebIDL spec, §3.3.10](https://webidl.spec.whatwg.org/#PutForwards)
- [ ] `[Replaceable]` [WebIDL spec, §3.3.11](https://webidl.spec.whatwg.org/#Replaceable)
- [ ] `[SameObject]` [WebIDL spec, §3.3.12](https://webidl.spec.whatwg.org/#SameObject) Very common, related to `[NewObject]`
- [ ] `[SecureContext]` [WebIDL spec, §3.3.13](https://webidl.spec.whatwg.org/#SecureContext) With `[Global]` and `[Exposed]`, maybe part of a realm initiative?
- [ ]

**Comment by Elchi3** [comment]
The discussion for iterable, maplike, setlike has been started here: https://github.com/orgs/mdn/discussions/707
