### ISSUE TITLE
New module landing: CSS Selectors

### ISSUE THREAD

**Issue by estelle** [openwebdocs/project#164]
Create landing page at https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors
 
 - [x] New page
 - [x] brief (5-paragraph approx) description
 - [ ] demonstration example
 - [x] properties / selectors
 - [x]  data types
 - [x] guides
 - [x]  associated properties
 - [x]  glossary terms
 
Other tasks:
- [X]  Move current landing page to a subpage of https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors
     - [X] https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors/selector_structure
     - [X] https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors/selectors_and_combinators
     - PR: https://github.com/mdn/content/pull/27601
- [x]  Pull out pseudo elements as they are now in their own module landing page ( #163 )
- [x] Update UI pseudo classes tutorial (PR: https://github.com/mdn/content/pull/27572)
- [x] Update :target guide https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_selectors/using_the__colon_target_pseudo-class_in_selectors
- [x] update case sensitivity of attr (PR: https://github.com/mdn/content/pull/27528/files)
- [x] File chrome ticket re: attr case sensitivity - https://bugs.chromium.org/p/chromium/issues/detail?id=1457844
- [x]  Create `|` namespace separator documentation. (PR: https://github.com/mdn/content/pull/27580)
- [x]  New module: CSS pseudo https://github.com/openwebdocs/project/issues/163
- [x] New module: cascade and inheritance https://github.com/openwebdocs/project/issues/165
