### ISSUE TITLE
Update CSS Cookbook

### ISSUE THREAD

**Issue by estelle** [openwebdocs/project#184]
### Problem statement

The Cookbook section is outdated, with indicators that well supported features are not fully supported yet.

### Proposed solutions

Update ALL. THE. THINGS.

### Task list

Upated the following pages and removed browser compact (except baseline, if present)

- [X] [Media objects](/en-US/docs/Web/CSS/Layout_cookbook/Media_objects)   https://github.com/mdn/content/pull/30142
- [x] [Columns](/en-US/docs/Web/CSS/Layout_cookbook/Column_layouts) https://github.com/mdn/content/pull/29961
- [x] [Center an element](/en-US/docs/Web/CSS/Layout_cookbook/Center_an_element) (https://github.com/mdn/content/pull/29609)
- [X] [Sticky footers](/en-US/docs/Web/CSS/Layout_cookbook/Sticky_footers)  https://github.com/mdn/content/pull/30146
- [X]  [Split navigation](/en-US/docs/Web/CSS/Layout_cookbook/Split_Navigation)   https://github.com/mdn/content/pull/30145
- [x]  [Breadcrumb navigation](/en-US/docs/Web/CSS/Layout_cookbook/Breadcrumb_Navigation)  (https://github.com/mdn/content/pull/29921)
- [x]  [List group with badges](/en-US/docs/Web/CSS/Layout_cookbook/List_group_with_badges) 
- [X] [Pagination](/en-US/docs/Web/CSS/Layout_cookbook/Pagination)  https://github.com/mdn/content/pull/30143/
- [X] [Card](/en-US/docs/Web/CSS/Layout_cookbook/Card) https://github.com/mdn/content/pull/29972
- [x] [Grid wrapper](/en-US/docs/Web/CSS/Layout_cookbook/Grid_wrapper)  https://github.com/mdn/content/pull/29998  

Also, 
- [x] [Contribute a recipe](/en-US/docs/Web/CSS/Layout_cookbook/Contribute_a_recipe)   https://github.com/mdn/content/pull/29993
