### ISSUE TITLE
OWD Project Proposal: empty Guide/ directory

### ISSUE THREAD

**Issue by teoli2003** [openwebdocs/project#185]
### Problem statement

The Web/Guide directory on mdn/content has about 15 pages that are old guides. Some are outdated, some were placed there because there was no better way.

We want to be able to better structure MDN documentation using a system like Divio's. It has 4 groups: Reference, How-to, Guides (Explanation), and Learn (Tutorials).

Currently the Guide directory goes in our way: we can't start building a new section there. We would like to empty it.

### Proposed solutions

Find a solution for each of the page that are still in this directory.

### Task list

- [x] **@teoli2003** [API](https://developer.mozilla.org/en-US/docs/Web/Guide/API) duplicate of Web/API but with a different sidebar (mdn/content#30620) 
- [x] **@teoli2003** [Audio and Video Delivery](https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery) 7 pages about delivering audio and video. (mdn/content#30766)
- [x] **@teoli2003** [Audio and Video manipulation](https://developer.mozilla.org/en-US/docs/Web/Guide/ (mdn/content#30766)Audio_and_video_manipulation) Introduction to canvas/webgl and to webaudio. (Split in two or redirect to one or the other User guide?)
- [ ] **@estelle** [CSS_Houdini](https://developer.mozilla.org/en-US/docs/Web/Guide/Houdini) Landing page of Houdini (transform into a Glossary page??? Too long) -> What to do with it?
- [x] **@estelle** [Graphics_on_the_Web](https://developer.mozilla.org/en-US/docs/Web/Guide/Graphics) kind of landing page listing APIs for Graphics. (mdn/content#30731)
- [x] **@wbamberg or @chrisdavidmills**  [Introduction_to_Web_Development](https://developer.mozilla.org/en-US/docs/Web/Guide/Introduction_to_Web_development) Landing page linking to API and external resources. _REDIRECT to some page in the Learning Area?_ (mdn/content#30666)
- [x] **@chrisdavidmills** [Mobile Web Development](https://developer.mozilla.org/en-US/docs/Web/Guide/Mobile) Vague intro to mobile development: a few points not to forget (screen size, …) Outdated as it only speaks about Responsible Web Design but don't mention things like Grid or flex. _Is there a place in the LA that has some more recent information and we could redirect there?_ **WARNING**: There are subpages. (mdn/content#31540)
- [x] **@teoli2003** [Optimization and Performance](https://developer.mozilla.org/en-US/docs/Web/Guide/Performance) Landing page with a few external links (mdn/content#30767)
- [x] **@teoli2003** [Parsing and serializing XML](https://developer.mozilla.org/en-US/docs/Web/Guide/Parsing_and_serializing_XML) (https://github.com/mdn/content/pull/30705)
- [x] **@estelle** [Printing](https://developer.mozilla.org/en-US/docs/Web/Guide/Printing) Short guide explaining what a print stylesheet is and an example with a button and using `beforeprint` events. _Redirect to https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries/Using_media_queries#targeting_media_types ?_ (mdn/content#30648)
- [x] **@estelle** [The Web Open Font Format (WOFF)](https://developer.mozilla.org/en-US/docs/Web/Guide/WOFF) Explanation about the WOFF format and how to use it (there because there was no better place)  _Under CSS fonts section?_ (mdn/content#30643)
- [x] **@estelle** [User inputs and worflow](https://developer.mozilla.org/en-US/docs/Web/Guide/User_input_methods) Vague introduction to events, with links to broken… Firefox OS pages (mdn/content#30646)
- [x] **@teoli2003** [Writing format-compatible web site](https://developer.mozilla.org/en-US/docs/Web/Guide/Writing_forward-compatible_websites) Speaks about prefixing with window, not doing UA-sniffing. (mdn/content#30622)

Once done:
- [ ]  Clean the content of the Web/Guide index page.

### Priority assessment

- **Effort**: 
- **Dependencies**: 
- **Community enablement**: 
- **Momentum**: 
- **Enabling learners**: 
- **Enabling professionals**:
- **Underrepresented topics / Ethical web**: 
- **Operational necessities**:
- **Addressing needs of the web industry**:

**Comment by wbamberg** [comment]
@chrisdavidmills can we just redirect https://developer.mozilla.org/en-US/docs/Web/Guide/Introduction_to_Web_development to https://developer.mozilla.org/en-US/docs/Learn ?

**Comment by estelle** [comment]
Three PRs so far. I'll do the next two tomorrow.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills can we just redirect https://developer.mozilla.org/en-US/docs/Web/Guide/Introduction_to_Web_development to https://developer.mozilla.org/en-US/docs/Learn ?

@wbamberg yes, definitely.

**Comment by estelle** [comment]
- [User inputs and worflow](https://developer.mozilla.org/en-US/docs/Web/Guide/User_input_methods) I reworked the user input to make it form focused, so https://github.com/mdn/content/pull/30646 has been updated.
- [Graphics_on_the_Web](https://developer.mozilla.org/en-US/docs/Web/Guide/Graphics): The graphics guide was deleted, the content moved and a redirect to the learn images page. Also added some of that content to the canvase element page as it was relevant.  https://github.com/mdn/content/pull/30731

**Comment by Userlugard** [comment]
Support help with user inputs and workflow

**Comment by chrisdavidmills** [comment]
@teoli2003 I'll handle the mobile web development pages

**Comment by estelle** [comment]
w00t!
