### ISSUE TITLE
Documentation for web platform features becoming widely available in 2024

### ISSUE THREAD

**Issue by Elchi3** [openwebdocs/project#196]
### Problem statement

The WebDX group has created an approximation called "[Baseline - high](https://github.com/web-platform-dx/web-features/blob/main/docs/baseline.md#wider-support-high-status)" that determines if a feature will be widely available to web developers.

Several web platform features implemented in recent years will reach this state within 2024. It would be good if we could guarantee that the 2024 Baseline high features are properly documented. Web developers want to learn about these features.

### Proposed solutions

According to BCD's current data there are about 635 features that, within 2024, can be considered "Baseline high". 
We should have a little checkup on the docs for these.
- Do we have a reference page and is it good?
- Do we need a guide for the feature/the feature set?
- ...

As BCD's data improves, 635 might not be the exact number of features, but we can re-query BCD later in the year to double-check. A spreadsheet that contains the list of features is here: https://docs.google.com/spreadsheets/d/1mBF49ZqtE_uZ58hR0xlb1uygqE7DOWuTHVaMLZd8auo/edit?resourcekey=0-yopuDeseph8VO-StzYjuBQ#gid=1238114670

### Task list

- [ ] Take a look at the list of features and group them.
- [ ] Agree on checkup criteria/level of improvement/doc quality we want to see for these
- [ ] Update/write the docs
- [ ] Double-check the list against BCD later in the year to see if there is more

### Priority assessment

- **Effort**: Large
- **Dependencies**: None. 
- **Community enablement**: We can share this project with anyone who wants to help. 
- **Momentum**: High. People will talk about these features in 2024 very likely.
- **Enabling learners**: n/a
- **Enabling professionals**: n/a
- **Underrepresented topics / Ethical web**: n/a
- **Operational necessities**: n/a
- **Addressing needs of the web industry**: I reckon it is good to show how newly, widely available features can be used on the web platform to do cool things.

### More information

Open Web Docs (OWD) is a non-profit collective funded by corporate and individual donations.

In order for this project to happen, please consider donating to OWD on https://opencollective.com/open-web-docs.
For more information on sponsorship and membership tiers, see https://openwebdocs.org/membership/

More information is available at https://openwebdocs.org/.
For questions, please reach out to [florian@openwebdocs.org](mailto:florian@openwebdocs.org).

**Comment by Elchi3** [comment]
We might want to break down this project and look at groups of features from the spreadsheet. For example:

1. AbortSignal
2. AuthenticatorResponse
3. BroadcastChannel
4. HTMLDialogElement
5. WebGL 2
6. Lock API
7. MediaSession
8. NavigationPrelooadManager
9. PerformanceNavigationTiming
10. PublicKeyCredential
11. RTC API improvements
12. ReadableStream/WritableStream/TransformStream
13. ResizeObserverSize
14. StorageManager
15. VisualViewport
16. Enhanced ImageBitmaps
17. CSS Layers
18. CSS cursor property
19. CSS Masks
20. More CSS scroll properties
21. More CSS text properties
22. SharedArrayBuffer and Atomics
23. BigInt64Arrays
24. Private Class fields
25. (a lot of misc features on their own)

**Comment by Elchi3** [comment]
I'm closing this project proposal for now. We haven't had the capacity to check the quality of the documentation for features that received a "baseline high" status in 2024. We can reopen this issue if we think this is a priority again.

In the meantime, we discover entirely undocumented APIs on https://openwebdocs.github.io/web-docs-backlog/. This work is probably higher priority for now than fixing up existing reference pages.
