### ISSUE TITLE
OWD project: WebDX web-features mapping 

### ISSUE THREAD

**Issue by Elchi3** [openwebdocs/project#208]
### Problem statement

This project is a continuation of https://github.com/openwebdocs/project/issues/169. The problem statement has been described previously:

> There is currently no consistent way to talk about web platform features as groups of features making it impossible to name a combination of features as a web platform capability.

> BCD records compatibility at quite a granular level. It provides data for each individual API, CSS property or HTTP header etc. and often also contains sub features describing more detailed facets of a feature. However, BCD has no concept of groups of features; they stand on their own. 

> MDN does some grouping but it does so incoherently. One mechanism is https://github.com/mdn/content/blob/main/files/jsondata/GroupData.json which is used by sidebars. It is largely based on how specifications group web platform features.

> caniuse.com allows varying granularity. You can record compatibility about a specific feature ("WebP image format"), or an about a group of features ("CSS Grid"). chromestatus.com is similar; its granularity varies a lot, too.

> As web developer, depending on where you look for compatibility information, this can lead to confusion. Chromestatus, caniuse and MDN might be talking about the same things, but aren't really. What's included in a group? And what is the support thereof? You might get different answers depending on where you look and this can prevent you from making a decision whether or not to use a web platform capability.

### Proposed solutions

The W3C WebDX Community Group has started to define feature-sets, see https://github.com/web-platform-dx/web-features

By creating a common nomenclature for web platform features, feature-set intends to support communication between web developers, browser vendors, standardization bodies, and other ecosystem participants. From Array to Cascade Layers to Offscreen Canvas, feature-set identifies, defines, and categorizes capabilities of the web platform that web developers care about.

### Task list

- [x] Map 3000 keys from the Browser Compat Data project to generate features as defined in the Web Features project. Create the data to contain names, descriptions, support statuses, or links to related data sources and documentation.
- [x] Review at least 750 keys mapped to features by other contributors (assuming these are available for review).
- [x] Provide synchronization of browser-compat-data keys between the mdn/browser-compat-data and web-platform-dx/web-features repositories. Contribute source code required to synchronize keys to their respective repositories on GitHub.
- [x] Provide Google with a monthly report on features added to Web Features for review. [Spreadsheet](https://docs.google.com/spreadsheets/d/185l3DZdtrYo9iZn3srRgWRkMM47gdIJ5iNETNgqgRzA/edit?gid=0#gid=0) 
- [x] Attend or support project meetings, such as the Web Platform DX Community Group meetings or coordination meetings, averaging not more than 2 hours per month.
- [x] Perform work on additional Web Feature Set Services as may be agreed by Google and OWD in writing (email sufficient).

### Priority assessment

- **Effort**: Large, until EOY 2024.
- **Dependencies**: BCD, web-features, WebDX. 
- **Community enablement**: WebDX community
- **Momentum**: High 
- **Enabling learners**: n/a
- **Enabling professionals**: n/a
- **Underrepresented topics / Ethical web**: n/a
- **Operational necessities**: n/a
- **Addressing needs of the web industry**: The mapping will be used on MDN, caniuse, tooling, status sites.

### More information

Open Web Docs (OWD) is a non-profit collective funded by corporate and individual donations.

This project is funded by Google. See https://opencollective.com/open-web-docs/conversations/google-statement-of-work-n104223-web-features-owd-aug-24-9paw0546

**Comment by Elchi3** [comment]
The above tasks are now completed!

(web-features' coverage of BCD is at 90% right now, and we will still try help out to make it to 100%, see https://github.com/web-platform-dx/web-features/issues/788 for an up-to-date tracking)
