### ISSUE TITLE
2024 H2 Projects

### ISSUE THREAD

**Issue by Elchi3** [openwebdocs/project#209]
## OWD H2 projects

This is a tracking issue for the projects the OWD team wants to focus on in the second half (H2) of 2024.

### BCD and web-features

This workstream is about improving browser compat data, so that web developers and other tools and initiatives can rely on BCD as the best source of compat information. 
**Leads:** Florian, Vinyl

- [ ] Run the collector for every new beta release of Chrome, Firefox, Safari during H2 2024 (Florian)
- [x] https://github.com/openwebdocs/project/issues/206 (Vinyl)
- [ ] https://github.com/openwebdocs/project/issues/208 (Florian + Vinyl)

### Content for interoperable and widely available features

This workstream looks at various data points (interop initiatives, baseline data, and BCD) to write and improve docs for web platform features that can be used widely across engines.
**Leads:** Estelle

- [ ] Create pages for all features marked as newly available in all browsers: https://openwebdocs.github.io/web-docs-backlog/recent/
- [ ] Docs for interop 2024 features?
- [ ] CSS modules? 
- [x] https://github.com/mdn/content/issues/35544

### Content to Secure the Web Forward

This workstream is about writing new documentation, especially guides, tutorials and how-tos about web security and to update reference docs to talk about security matters. See the workshop report https://www.w3.org/2023/03/secure-the-web-forward/report.html for our 2023 research about this topic.
**Leads:** Will, Florian

- [ ] [Web Security docs for MDN](https://github.com/openwebdocs/project/issues/198)

### Research workstream

This workstream is about researching and preparing future OWD projects.

- [WebView docs](https://github.com/openwebdocs/project/issues/111) (Florian joined the W3C WebView CG and will figure out how we can help in the future with docs and compat data)
- [Doc structures for WebIDL concepts](https://github.com/openwebdocs/project/issues/159) (Will to do parts of this by proposing documentation guidelines and possibly tools to help)

**Comment by Elchi3** [comment]
Closing. It was a great year! :)
https://openwebdocs.org/content/reports/2024/
