### ISSUE TITLE
Project: Add missing "widely available" CSS attributes

### ISSUE THREAD

**Issue by estelle** [openwebdocs/project#210]
### Problem statement

There are 29 "widely supported" baseline CSS properties missing from MDN documentation. These CSS properties need to be documented.

### Proposed solutions

add missing pages.

### Task list

- [x] [`clip-rule`](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-rule)
- [x] [`color-interpolation-filters`](https://developer.mozilla.org/en-US/docs/Web/CSS/color-interpolation-filters)
- [x] [`cx`](https://developer.mozilla.org/en-US/docs/Web/CSS/cx)
- [x] [`cy`](https://developer.mozilla.org/en-US/docs/Web/CSS/cy)
- [x] [`dominant-baseline`](https://developer.mozilla.org/en-US/docs/Web/CSS/dominant-baseline)
- [x] [`fill`](https://developer.mozilla.org/en-US/docs/Web/CSS/fill)
- [x] [`fill-opacity`](https://developer.mozilla.org/en-US/docs/Web/CSS/fill-opacity)
- [x] [`fill-rule`](https://developer.mozilla.org/en-US/docs/Web/CSS/fill-rule)
- [x] [flood-color](https://drafts.fxtf.org/filter-effects-1/#FloodColorProperty)
- [x] [flood-opacity](https://drafts.fxtf.org/filter-effects-1/#FloodOpacityProperty)
- [x] [lighting-color](https://drafts.fxtf.org/filter-effects-1/#LightingColorProperty)
- [x] [`marker`](https://developer.mozilla.org/en-US/docs/Web/CSS/marker) 
- [x] [`marker-end`](https://developer.mozilla.org/en-US/docs/Web/CSS/marker-end)
- [x] [`marker-mid`](https://developer.mozilla.org/en-US/docs/Web/CSS/marker-mid)
- [x] [`marker-start`](https://developer.mozilla.org/en-US/docs/Web/CSS/marker-start)
- [x] [`r`](https://developer.mozilla.org/en-US/docs/Web/CSS/r)
- [x] [`rx`](https://developer.mozilla.org/en-US/docs/Web/CSS/rx)
- [x] [`ry`](https://developer.mozilla.org/en-US/docs/Web/CSS/ry)
- [x] [`shape-rendering`](https://developer.mozilla.org/en-US/docs/Web/CSS/shape-rendering)
- [x] [`stop-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/stop-color)
- [x] [`stop-opacity`](https://developer.mozilla.org/en-US/docs/Web/CSS/stop-opacity)
- [x] [`stroke`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke)
- [x] [`stroke-dasharray`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-dasharray)
- [x] [`stroke-dashoffset`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-dashoffset)
- [x] [`stroke-linecap`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-linecap)
- [x] [`stroke-linejoin`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-linejoin)
- [x] [`stroke-miterlimit`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-miterlimit)
- [x] [`stroke-opacity`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-opacity)
- [x] [`stroke-width`](https://developer.mozilla.org/en-US/docs/Web/CSS/stroke-width)
- [x] [`text-anchor`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-anchor)
- [x] [`vector-effect`](https://developer.mozilla.org/en-US/docs/Web/CSS/vector-effect)
- [x] [`word-wrap`](https://developer.mozilla.org/en-US/docs/Web/CSS/word-wrap)
- [x] [`x`](https://developer.mozilla.org/en-US/docs/Web/CSS/x)
- [x] [`y`](https://developer.mozilla.org/en-US/docs/Web/CSS/y)

### What did you expect to see?

these properties documented

### Do you have any supporting links, references, or citations?

https://openwebdocs.github.io/web-docs-backlog/baseline/

**Comment by Elchi3** [comment]
This is all done! Wonderful! 🎉
