### ISSUE TITLE
Project: Document supported missing CSS properties

### ISSUE THREAD

**Issue by estelle** [openwebdocs/project#211]
### Problem statement

Some CSS properties are supported by one or more browsers, but are not documented on MDN.

### Proposed solutions

Document the missing properties

### Task list

- [ ] `buffered-rendering` (https://github.com/mdn/browser-compat-data/issues/24053)
- [ ] `color-rendering` (https://github.com/mdn/browser-compat-data/issues/24053)
- [ ] `glyph-orientation-horizontal` (https://github.com/mdn/browser-compat-data/issues/24052)
- [ ] `mask-position-x` (-webkit-mask-position-x documented, but un-prefixed version exists in Safari TP)
- [ ] `mask-position-y` (-webkit-mask-position-y documented, but un-prefixed version exists in Safari TP)
- [ ] `text-box-edge` (https://caniuse.com/?search=text-box-edge, exists in Safari TP)
- [ ] `text-box-trim` (https://caniuse.com/?search=text-box-trim, exists in Safari TP)

Possibly:

- `moz-window-dragging`

### Priority assessment

- **Effort**: 
- **Dependencies**: 
- **Community enablement**: 
- **Momentum**: 
- **Enabling learners**: 
- **Enabling professionals**:
- **Underrepresented topics / Ethical web**: 
- **Operational necessities**:
- **Addressing needs of the web industry**:

### More information

Open Web Docs (OWD) is a non-profit collective funded by corporate and individual donations.

In order for this project to happen, please consider donating to OWD at https://opencollective.com/open-web-docs.
For more information on sponsorship and membership tiers, see https://openwebdocs.org/membership/

More information is available at https://openwebdocs.org/.
For questions, please reach out to florian@openwebdocs.org.

**Comment by estelle** [comment]
From the issues brought up in the [CSS longhand properties PR](https://github.com/mdn/content/pull/35108), this issue addresses the following properties:

* buffered-rendering
* color-rendering
* glyph-orientation-horizontal
* mask-position-x
* mask-position-y
* text-box-edge
* text-box-trim

30 properties are addressed by [CSS SVG properties project](https://github.com/openwebdocs/project/issues/210)

Future research is needed for an additional 10 properties that are supported by at least one browser but are NOT in the backlog of missing properties:

* alignment-baseline
* alt
* app-region
* baseline-shift
* baseline-source
* glyph-orientation-vertical
* ime-mode
* object-view-box
* speak
* view-transition-class

**Comment by Elchi3** [comment]
@estelle can we close this?
