### ISSUE TITLE
Interop: Forms

### ISSUE THREAD

**Issue by estelle** [openwebdocs/project#212]
- [x] Review Form documentation:
	- [x] Learn Forms
	- [x] Web form building blocks
	- [ ] Your first form
	- [x] How to structure a web form
	- [x] [Basic form controls](https://developer.mozilla.org/en-US/docs/Learn/Forms/Basic_native_form_controls) [#35510](https://github.com/mdn/content/pull/35510)
	- [x] [Newer inputs](https://developer.mozilla.org/en-US/docs/Learn/Forms/HTML5_input_types) [#35514](https://github.com/mdn/content/pull/35514)
	- [x] [Other form controls](https://developer.mozilla.org/en-US/docs/Learn/Forms/Other_form_controls) [#35512](https://github.com/mdn/content/pull/35512)
	- [x] [Styling web forms](https://developer.mozilla.org/en-US/docs/Learn/Forms/Styling_web_forms)
	- [x] Advanced form styling
	- [x] UI pseudo-classes
	- [x] [Client-side form validation](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation)
	- [x] Sending form data
- [x] Advanced web form techniques
	- [x] How to build custom form controls
	- [x] [Sending forms through JavaScript](https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_forms_through_JavaScript)
	- [ ] CSS property compatibility table for form controls
	- [x] [HTML forms in legacy browsers](https://developer.mozilla.org/en-US/docs/Learn/Forms/HTML_forms_in_legacy_browsers)
- [x] Remove mentions of "when supported" on all form control pages
- [x] Remove screen shots of the controls themselves (Retain dynamic keyboard and error msg images)
- [ ] Form submission target
- [ ] Constraint validation
- [ ] Review related CSS properties, including:
	- [x] [`appearance`](https://developer.mozilla.org/en-US/docs/Web/CSS/appearance)
	- [ ] [`accent-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color)
	- [ ] [`resize`](https://developer.mozilla.org/en-US/docs/Web/CSS/resize)
	- [ ] [`pointer-events`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events)
	- [ ] [`user-select`](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select)
	- [ ] [`field-sizing`](https://developer.mozilla.org/en-US/docs/Web/CSS/field-sizing)
	- [ ] [`input-security`](https://developer.mozilla.org/en-US/docs/Web/CSS/input-security)
	- [x] [`caret-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/caret-color)
	- [ ] [`caret-animation`](https://developer.mozilla.org/en-US/docs/Web/CSS/caret-animation)
	- [ ] [`caret-shape`](https://developer.mozilla.org/en-US/docs/Web/CSS/caret-shape)
	- [ ] [`caret`](https://developer.mozilla.org/en-US/docs/Web/CSS/caret)
- [x] Check `<marquee>` element status (https://github.com/mdn/content/pull/36435)
- [ ] Sizing for `<select>`
- [x] DOM reflection-forms
- [ ] replace before load
- [x] [Forms API](https://developer.mozilla.org/en-US/docs/Web/API/Document/forms)
- [x] Missing documentation - complete https://github.com/openwebdocs/project/issues/213

**Comment by estelle** [comment]
- Form control appearance:
	- [ ] `<input>`
	- [ ] `<input type="text">`
	- [ ] `<input type="TEXT">`
	- [X] `<input type="search">`
	- [ ] `<input type="tel">`
	- [ ] `<input type="url">`
	- [ ] `<input type="email">`
	- [ ] `<input type="password">`
	- [ ] `<input type="date">`
	- [ ] `<input type="month">`
	- [ ] `<input type="week">`
	- [ ] `<input type="time">`
	- [ ] `<input type="datetime-local">`
	- [ ] `<input type="number">`
	- [ ] `<input type="range">`
	- [ ] `<input type="color">`
	- [ ] `<input type="checkbox">`
	- [ ] `<input type="radio">`
	- [ ] `<input type="submit">`
	- [ ] `<input type="reset">`
	- [ ] `<input type="button">`
	- [ ] `<input type="unknowntype">`
	- [ ] `<select>`
	- [ ] `<select multiple="">`
	- [ ] `<select size="2">`
	- [ ] `<button>`
	- [ ] `<textarea>`
	- [ ] `<meter>`
	- [ ] `<progress>`
	- [ ] `<input type="hidden">`
	- [ ] `<input type="HIDDEN">`
	- [ ] `<input type="file">`
	- [ ] `<input type="image">`
	- [ ] `<form>`
	- [ ] `<fieldset>`
	- [ ] `<label>`
	- [ ] `<summary>`
	- [ ] `<video>`
	- [ ] `<video controls="">`
	- [ ] `<menuitem>`
	- [ ] `<marquee>`
	- [ ] `<keygen>`
- [ ] Form sumbission target
	- [ ] https://bugs.chromium.org/p/chromium/issues/detail?id=1234409
	- [ ] https://bugs.webkit.org/show_bug.cgi?id=235407
	- [ ] https://bugs.chromium.org/p/chromium/issues/detail?id=1234409
- [ ] Validation
	- [ ] validate
	- [ ] validity-badInput
	- [ ] validity-customError
	- [ ] validity-patternMismatch
	- [ ] validity-rangeOverflow
	- [ ] validity-rangeUnderflow
	- [ ] validity-tooLong
	- [ ] validity-tooShort
	- [ ] validity-typeMismatch
	- [ ] validity-valid
	- [ ] validity-valueMissing
	- [ ] willValidate-datalist
	- [ ] willValidate
	- [ ] number input: dynamic-value: no-change
	- [ ] pattern: dynamic-value
	- [ ] input: willvalidate
	- [ ] radio: valueMissing
- [ ] CSS
	- [x] `appearance`
	- [ ] `accent-color`
	- [ ] `resize`
	- [ ] `pointer-events`
	- [ ] `user-select`
	- [ ] `field-sizing`
	- [ ] `input-security`
	- [x] 'caret-color'
	- [x] 'caret-animation'
	- [ ] 'caret-shape'
	- [ ] `caret`

- [ ] HTML rendering
   - [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1733789
   - [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1708370
   - [ ] https://bugs.chromium.org/p/chromium/issues/detail?id=1220220
   - [ ] Toggle display
   - [ ] select sizing
   - [ ] `<input>` placeholder lineheight
   - [ ] `<marquee>`
   - [ ] textarea `overflow`: expect "visible" but got "auto"?

- [ ] DOM reflection-forms? 
   - [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1878982
   - [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=675943

- [ ] Navigating across documents / replace before load: 
    - [ ] https://bugs.webkit.org/show_bug.cgi?id=227299
    - [ ] https://bugzilla.mozilla.org/show_bug.cgi?id=1718123

- [ ] https://developer.mozilla.org/en-US/docs/Web/API/Document/forms

- [ ] Learn Forms
	- [ ] Web form building blocks
	- [ ] Your first form
	- [ ] How to structure a web form
	- [x] [Basic form controls](https://developer.mozilla.org/en-US/docs/Learn/Forms/Basic_native_form_controls) [#35510](https://github.com/mdn/content/pull/35510)
	- [x] [Newer inputs](https://developer.mozilla.org/en-US/docs/Learn/Forms/HTML5_input_types) [#35514](https://github.com/mdn/content/pull/35514)
	- [x] [Other form controls](https://developer.mozilla.org/en-US/docs/Learn/Forms/Other_form_controls) [#35512](https://github.com/mdn/content/pull/35512)
	- [ ] Advanced form styling
	- [ ] UI pseudo-classes
	- [ ] [Client-side form validation](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation)
	- [ ] Sending form data
- [ ] Advanced web form techniques
	- [ ] How to build custom form controls
	- [ ] [Sending forms through JavaScript](https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_forms_through_JavaScript)
	- [ ] CSS property compatibility table for form controls\

**Comment by Josh-Cena** [comment]
You may be interested in also closing the following issues:

- https://github.com/mdn/content/issues/33283
- https://github.com/mdn/content/issues/31250
- https://github.com/mdn/content/issues/28375
- https://github.com/mdn/content/issues/24304
- https://github.com/mdn/content/issues/16949

**Comment by yashrajbharti** [comment]
@estelle  Can I take on 

[caret-animation](https://developer.mozilla.org/en-US/docs/Web/CSS/caret-animation)
[caret-shape](https://developer.mozilla.org/en-US/docs/Web/CSS/caret-shape)
[caret](https://developer.mozilla.org/en-US/docs/Web/CSS/caret)

I have already worked on [Caret Position APIs](https://github.com/mdn/content/pull/40527)

(PS: ~~Also can you kindly check your mail!~~ Ty!)

**Comment by estelle** [comment]
> [caret-animation](https://developer.mozilla.org/en-US/docs/Web/CSS/caret-animation) [caret-shape](https://developer.mozilla.org/en-US/docs/Web/CSS/caret-shape) [caret](https://developer.mozilla.org/en-US/docs/Web/CSS/caret)

`caret-animation` was done recently.
i don't think shape or the shorthand are supported in any browsers yet (they're not in https://openwebdocs.github.io/web-docs-backlog/all/), caret relies on caret-shape, and caret-shape hasn't moved recently but igalia seems to be working on it: https://issues.chromium.org/issues/353713061 and caret-shape but not caret was visible in canary 141.... so yes, feel free to work on it, but it won't be published until a browser supports it.... which may actually be soon.
