### ISSUE TITLE
OWD Project: Missing form-related API docs

### ISSUE THREAD

**Issue by estelle** [openwebdocs/project#213]
### Problem statement

There are missing form API docs that are baseline

### Proposed solutions

We should add these documents to MDN

### Task list

- [x] [`HTMLButtonElement.reportValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/reportValidity)
- [x] [`HTMLButtonElement.checkValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/checkValidity)
- [x] [`HTMLButtonElement.form`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/form)
- [x] [`HTMLButtonElement.formAction`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/formAction)
- [x] [`HTMLButtonElement.formEnctype`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/formEnctype)
- [x] [`HTMLButtonElement.formMethod`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/formMethod)
- [x] [`HTMLButtonElement.formNoValidate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/formNoValidate)
- [x] [`HTMLButtonElement.formTarget`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/formTarget)
- [x] [`HTMLButtonElement.name`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/name)
- [x] [`HTMLButtonElement.setCustomValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/setCustomValidity)
- [x] [`HTMLButtonElement.validationMessage`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/validationMessage)
- [x] [`HTMLButtonElement.validity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/validity)
- [x] [`HTMLButtonElement.value`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/value)
- [x] [`HTMLButtonElement.willValidate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLButtonElement/willValidate)
- [x] [`HTMLDataListElement.options`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDataListElement/options)
- [x] [`HTMLFieldSetElement.reportValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/reportValidity)
- [x] [`HTMLFieldSetElement.elements`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/elements)
- [x] [`HTMLFieldSetElement.type`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/type)
- [x] [`HTMLFieldSetElement.name`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/name)
- [x] [`HTMLFieldSetElement.checkValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/checkValidity)
- [x] [`HTMLFieldSetElement.disabled`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/disabled)
- [x] [`HTMLFieldSetElement.form`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/form)
- [x] [`HTMLFieldSetElement.setCustomValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/setCustomValidity)
- [x] [`HTMLFieldSetElement.validationMessage`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/validationMessage)
- [x] [`HTMLFieldSetElement.validity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/validity)
- [x] [`HTMLFieldSetElement.willValidate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFieldSetElement/willValidate)
- [x] [`HTMLFormElement.autocomplete`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/autocomplete)
- [x] [`HTMLFormElement.checkValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/checkValidity)
- [x] [`HTMLFormElement.noValidate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/noValidate)
- [x] [`HTMLInputElement.list`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/list)
- [x] [`HTMLInputElement.minLength`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/minLength)
- [x] [`HTMLInputElement.valueAsDate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/valueAsDate)
- [x] [`HTMLInputElement.accept`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/accept)
- [x] [`HTMLInputElement.alt`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/alt)
- [x] [`HTMLInputElement.autocomplete`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/autocomplete)
- [x] [`HTMLInputElement.checked`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/checked)
- [x] [`HTMLInputElement.defaultChecked`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/defaultChecked)
- [x] [`HTMLInputElement.defaultValue`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/defaultValue)
- [x] [`HTMLInputElement.form`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/form)
- [x] [`HTMLInputElement.formAction`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/formAction)
- [x] [`HTMLInputElement.formEnctype`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/formEnctype)
- [x] [`HTMLInputElement.formMethod`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/formMethod)
- [x] [`HTMLInputElement.formNoValidate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/formNoValidate)
- [x] [`HTMLInputElement.formTarget`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/formTarget)
- [x] [`HTMLInputElement.height`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/height)
- [x] [`HTMLInputElement.indeterminate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/indeterminate)
- [x] [`HTMLInputElement.max`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/max)
- [x] [`HTMLInputElement.maxLength`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/maxLength)
- [x] [`HTMLInputElement.min`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/min)
- [x] [`HTMLInputElement.name`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/name)
- [x] [`HTMLInputElement.pattern`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/pattern)
- [x] [`HTMLInputElement.placeholder`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/placeholder)
- [x] [`HTMLInputElement.readOnly`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/readOnly)
- [x] [`HTMLInputElement.required`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/required)
- [x] [`HTMLInputElement.size`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/size)
- [x] [`HTMLInputElement.src`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/src)
- [x] [`HTMLInputElement.step`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/step)
- [x] [`HTMLInputElement.validationMessage`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/validationMessage)
- [x] [`HTMLInputElement.validity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/validity)
- [x] [`HTMLInputElement.value`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/value)
- [x] [`HTMLInputElement.valueAsNumber`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/valueAsNumber)
- [x] [`HTMLInputElement.width`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/width)
- [x] [`HTMLInputElement.willValidate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/willValidate)
- [x] [`HTMLLegendElement.form`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLegendElement/form)
- [x] [`HTMLMeterElement.high`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMeterElement/high)
- [x] [`HTMLMeterElement.low`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMeterElement/low)
- [x] [`HTMLMeterElement.max`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMeterElement/max)
- [x] [`HTMLMeterElement.min`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMeterElement/min)
- [x] [`HTMLMeterElement.optimum`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMeterElement/optimum)
- [x] [`HTMLMeterElement.value`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMeterElement/value)
- [x] [`HTMLModElement.cite`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLModElement/cite)
- [x] [`HTMLModElement.dateTime`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLModElement/dateTime)
- [x] [`HTMLObjectElement.reportValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/reportValidity)
- [x] [`HTMLOptGroupElement.disabled`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptGroupElement/disabled)
- [x] [`HTMLOptGroupElement.label`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptGroupElement/label)
- [x] [`HTMLOptionElement.defaultSelected`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/defaultSelected)
- [x] [`HTMLOptionElement.disabled`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/disabled)
- [x] [`HTMLOptionElement.form`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/form)
- [x] [`HTMLOptionElement.index`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/index)
- [x] [`HTMLOptionElement.label`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/label)
- [x] [`HTMLOptionElement.selected`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/selected)
- [x] [`HTMLOptionElement.text`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/text)
- [x] [`HTMLOptionElement.value`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/value)
- [x] [`HTMLOptionsCollection.add`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionsCollection/add)
- [x] [`HTMLOptionsCollection.length`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionsCollection/length)
- [x] [`HTMLOptionsCollection.remove`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionsCollection/remove)
- [x] [`HTMLOptionsCollection.selectedIndex`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionsCollection/selectedIndex)
- [x] [`HTMLOutputElement.reportValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/reportValidity)
- [x] [`HTMLOutputElement.checkValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/checkValidity)
- [x] [`HTMLOutputElement.defaultValue`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/defaultValue)
- [x] [`HTMLOutputElement.form`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/form)
- [x] [`HTMLOutputElement.htmlFor`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/htmlFor)
- [x] [`HTMLOutputElement.name`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/name)
- [x] [`HTMLOutputElement.setCustomValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/setCustomValidity)
- [x] [`HTMLOutputElement.type`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/type)
- [x] [`HTMLOutputElement.validationMessage`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/validationMessage)
- [x] [`HTMLOutputElement.validity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/validity)
- [x] [`HTMLOutputElement.value`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/value)
- [x] [`HTMLOutputElement.willValidate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLOutputElement/willValidate)
- [x] [`HTMLQuoteElement.cite`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLQuoteElement/cite)
- [x] [`HTMLSelectElement.autocomplete`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/autocomplete)
- [x] [`HTMLSelectElement.reportValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/reportValidity)
- [x] [`HTMLSelectElement.length`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/length)
- [x] [`HTMLSelectElement.multiple`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/multiple)
- [x] [`HTMLSelectElement.name`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/name)
- [x] [`HTMLSelectElement.required`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/required)
- [x] [`HTMLSelectElement.size`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/size)
- [x] [`HTMLSelectElement.validationMessage`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/validationMessage)
- [x] [`HTMLSelectElement.validity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/validity)
- [x] [`HTMLSelectElement.willValidate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/willValidate)
- [x] [`HTMLTextAreaElement.autocomplete`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/autocomplete)
- [x] [`HTMLTextAreaElement.selectionDirection`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/selectionDirection)
- [x] [`HTMLTextAreaElement.setRangeText`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/setRangeText)
- [x] [`HTMLTextAreaElement.reportValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/reportValidity)
- [x] [`HTMLTextAreaElement.minLength`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/minLength)
- [x] [`HTMLTextAreaElement.textLength`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/textLength)
- [x] [`HTMLTextAreaElement.checkValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/checkValidity)
- [x] [`HTMLTextAreaElement.cols`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/cols)
- [x] [`HTMLTextAreaElement.defaultValue`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/defaultValue)
- [x] [`HTMLTextAreaElement.disabled`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/disabled)
- [x] [`HTMLTextAreaElement.form`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/form)
- [x] [`HTMLTextAreaElement.maxLength`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/maxLength)
- [x] [`HTMLTextAreaElement.name`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/name)
- [x] [`HTMLTextAreaElement.placeholder`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/placeholder)
- [x] [`HTMLTextAreaElement.readOnly`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/readOnly)
- [x] [`HTMLTextAreaElement.required`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/required)
- [x] [`HTMLTextAreaElement.rows`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/rows)
- [x] [`HTMLTextAreaElement.select`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/select)
- [x] [`HTMLTextAreaElement.selectionEnd`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/selectionEnd)
- [x] [`HTMLTextAreaElement.selectionStart`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/selectionStart)
- [x] [`HTMLTextAreaElement.setCustomValidity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/setCustomValidity)
- [x] [`HTMLTextAreaElement.setSelectionRange`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/setSelectionRange)
- [x] [`HTMLTextAreaElement.validationMessage`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/validationMessage)
- [x] [`HTMLTextAreaElement.validity`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/validity)
- [x] [`HTMLTextAreaElement.value`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/value)
- [x] [`HTMLTextAreaElement.willValidate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/willValidate)
- [x] [`HTMLTextAreaElement.wrap`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/wrap)

### More information

Open Web Docs (OWD) is a non-profit collective funded by corporate and individual donations.

In order for this project to happen, please consider donating to OWD at https://opencollective.com/open-web-docs.
For more information on sponsorship and membership tiers, see https://openwebdocs.org/membership/

More information is available at https://openwebdocs.org/.
For questions, please reach out to florian@openwebdocs.org.

**Comment by estelle** [comment]
Completed in https://github.com/mdn/content/issues/35544
