### ISSUE TITLE
OWD project: Making MDN syntax boxes beginner friendly

### ISSUE THREAD

**Issue by Elchi3** [openwebdocs/project#26]
This project proposes that we work on enhancing MDN syntax boxes in MDN JavaScript and Web API docs. 

Originally proposed a few years ago on the MDN mailing list https://groups.google.com/g/mozilla.dev.mdc/c/eS12O5mAI-A/m/J1Qd-HajBgAJ and recently re-proposed on mdn/content: https://github.com/mdn/content/issues/2202

Some work in this direction has happened, but it has only been tested on a few pages and not rolled out widely enough. Also, talking to actual beginners, and doing user research and A/B tests would help to further enhance this section.

# Problem statement

The [syntax section](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice#syntax) on MDN helps readers to quickly get to the gist of what an API's method or constructor does. Often, the snippets in the syntax section are copy-pasted. Readers might know what `splice` does, but they don't always know the parameters, for example.

Currently, syntax sections are often using the more complex BNF notation. For example, `array.splice(start[, deleteCount[, item1[, item2[, ...]]]])` confuses readers. 

Also "[]" is an array in JS, so a method like `arr.sort([compareFunction])` can look confusing.

# Priority assessment

This table checks this project against the [OWD prioritization criteria](https://github.com/openwebdocs/project/blob/main/steering-committee/prioritization-criteria.md).

| Criteria 	| Assessment |
|-----------|------------|
| Effort | Large. Affects lots of pages. The work on each page is relatively tiny, though. |
| Dependencies | None. Working with user research and/or A/B tests would allow us to find out more and do better, though. |
| Community enablement | Yes. This task is quite self-contained and contributions to update as many pages as possible are welcome |
| Momentum | N/A |
| Enabling learners | Very much helps learners as it simplifies the docs and avoids confusion |
| Enabling professionals | Not really but a detailed look at the section section will make things consistent |
| Underrepresented topics / ethical web | N/A |
| Operational necessities | N/A |
| Addressing needs of the Web industry | N/A |

# Proposed solutions
- As a first step, we should eliminate confusions that come with BNF notations. The proposal that is most promising seems to be to switch to multiple lines. We should roll this out to a sensible amount of docs and check if works better and avoids the confusions readers currently face.
- At a later step, we can think about how to make these sections even better. For example, an idea by Hamish Willee is to also add types to the syntax. This would probably address a need the TypeScript community has. More research is needed to confirm this, though.
- Ideally, we work with users and/or A/B tests. This adds a dependency though. So, we will probably roll out the multi-line version and see how people react to it to confirm the approach. 

# Task list

- [x] Agree on a way forward to avoid the BNF syntax. Done! We're going with multiple lines for now.
- [x] Update MDN contribution docs. Done by Hamish Willee!
- [x] Update MDN JS docs

# Follow ups: 
- Update MDN API docs
- Do more research around adding types

**Comment by sideshowbarker** [comment]
> So, we will probably roll out the multi-line version and see how people react to it to confirm the approach.

I think that’s the best approach in this case — get the changes out in production on scale, and see what feedback/bugs/complaints/likes we get. I suspect we’ll not end up getting much feedback, because from an information-design perspective, it’s kind of a “it just works” case for readers. What I mean it, I think readers will find it more clear than what we had previously, but they won’t even notice the added clarity. (I think there a very few people other than us who will be comparing it to what it looked like previously.)

**Comment by Elchi3** [comment]
I've closed the MDN issue: https://github.com/mdn/content/issues/2202#issuecomment-833418442. I think we are done with this for the moment. So, closing here, too.

There are two follow-up projects that could be done from here: 
- Update MDN API docs to also use this throughout (to not wait until pages are updated when we spot the old syntax blocks)
- Do more research around adding types / return values.

We can keep these follow ups in mind as we plan new projects and evaluate new ideas. They will need to be re-assessed in terms of priorities then, too.
