### ISSUE TITLE
Put browser-compat info in front-runner everywhere on MDN

### ISSUE THREAD

**Issue by teoli2003** [openwebdocs/project#36]
As a prerequesite for completing issue #24, a quaterly goal of OWD, we need to have the browser-compat clause in the front-runner of any relevant page of MDN.

I have a Python script helping me, but we are speaking about updating 6000+ pages of MDN. I will break this down into small(ish), and manageable, PRs.

Here I will track progress:

- [x] api/a* – PR mdn/content#5400 – 215 files
- [x] api/b* – PR mdn/content#5401 – 186 files
- [x] api/c* – PR mdn/content#5404 – 418 files
- [x] api/d* – PR mdn/content#5406 – 343 files
- [x] api/e* – PR mdn/content#5407 – 265 files
- [x] api/f* – PR mdn/content#5409 – 144 files
- [x] api/g* – PR mdn/content#5410 – 135 files
- [x] api/h* – PR mdn/content#5411 – 426 files
- [x] api/i* – PR mdn/content#5412 – 173 files
- [x] api/[jkl]* – PR mdn/content#5413 – 69 files
- [x] api/m* – PR mdn/content#5415 – 334 files
- [x] api/n* – PR mdn/content#5418 – 177 files
- [x] api/[opq]* – PR mdn/content#5536 – 414 files
- [x] api/r* – PR mdn/content#5423 – 483 files
- [x] api/s* – PR mdn/content#5426 – 536 files
- [x] api/t* – PR mdn/content#5427 – 154 files
- [x] api/u* – PR mdn/content#5428 – 99 files
- [x] api/v* – PR mdn/content#5441 – 120 files
- [x] api/w* – PR mdn/content#5444 – 504 files
- [x] api/[xyz]* – PR mdn/content#5447 – 203 files

Subtotal: standard api: 5398 files

- [x] api/[abc]* (unusual) – PR mdn/content#5551 – 10 files
- [x] api/[d-q]* (unusual) – PR mdn/content#5568 – 10 files (and follow-up PR mdn/content#5598 )
- [x] api/[r-z]* (unusual) – PR mdn/content#5586 – 30 files 
- [x] css/* – No PR (already done) – 0 file
- [x] html/Elements/input/* – No PR (already done) – 0 file (Done by @Elchi3 in mdn/content#5166)
- [x] html/Elements/* – PR mdn/content#5471 – 132 files
- [x] html/Elements (unusual)  – PR mdn/content#5502 – 4 files
- [x] html/Global_attributes/* – No PR (already done) – 0 file (Done by @Elchi3 in mdn/content#5149)
- [x] manifest/* – No PR (already done) – 0 file (Done by @Elchi3 in mdn/content#5164)
- [x] http/headers/CSP – PR mdn/content#5468 – 32 files
- [x] http/headers/* – PR mdn/content#5469 – 124 files
- [x] http/status/* – PR mdn/content#5470 – 30 files
- [x] http/methods/* (and data_URL) – PR mdn/content#5472 – 10 files
- [x] http/* (unusual) – PR mdn/content#5538 – 2 files
- [x] javascript/* – No PR (already done) – 0 file (Done by @Elchi3; see mdn/content#4726 and mdn/content#4594)
- [x] mathml/* – PR mdn/content#5494 – 29 files
- [x] svg/* – PR mdn/content#5496 – 277 files
- [x] xpath/* & xslt/* – PR mdn/content#5500 – 3 files
- [x] mozilla/add-ons/webextensions/api/* – PR mdn/content#5476 – 400 files
- [x] mozilla/add-ons/webextensions/manifest.json/*  – PR mdn/content#5492 – 34 files
- [x] mozilla/add-ons/webextensions/* (unusual)  – PR mdn/content#5504 – 131 files
- [x] webdriver – PR mdn/content#5592 – 11 files
- [x] missing bcd in api/* – PR mdn/content#5630 – 8 files

Special cleaning PR
- [x] Remove duplicate RTCPeerConnection_idpvalidationerror_event PR mdn/content#5570
- [x] Merge OffscreenCanvas.toBlob into OffscreenCanvas.convertToBlob PR mdn/content#5590
- [x] Merge XMLHttpRequestresponsetype into XMLHttpRequest.ResponseType PR mdn/content#5664
- [x] Merge ServiceWorkerState into ServiceWorker.state PR mdn/content#5660
- [ ] Merge AudioContextLatencyCategory into AudioContextOptions.latencyHint

Update documentation about it:
- [x] Update BCD documentation
- [x] Update Page templates – PR mdn/content#5544 – 12 files  
- [x]     [Partial duplicate of mdn/content#5225; be sure to integrate discussed points]

**Comment by teoli2003** [comment]
I think we are done with this! @wbamberg , @Elchi3 : if you something more to be done here, please reopen it.

🍾  BCD is in front-runner for the whole of MDN, yeah! 🍾

**Comment by Elchi3** [comment]
Thanks for all your help, @teoli2003! 🍾 🎉
