### ISSUE TITLE
OWD Project Proposal to add the Web Monetization Meta to MDN Docs

### ISSUE THREAD

**Issue by uchibeke** [openwebdocs/project#37]
This issue proposing adding a [Web Monetization](webmonetization.org) meta tag to MDN to enable OWD to seamlessly accept micropayments/donations from Web Monetized users.

Users visiting MDN already have a subscription from a Web Monetization provider and do not have to pay additional fees to support MDN when they use the docs.

## Problem Statement
MDN is visited by many users who already have a subscription from a Web Monetization provider. However, even though they do not need to take any other action, OWD is currently not taking micropayments/donations from the users visiting the site.

The impact of this is that we are losing $0.36/hour (as of today) for every hour a Web Monetized user visits MDN. This donation could go towards covering some OWD costs or be donated to organizations like Creative Commons, Web Foundation, or Contract for the Web since they already have an Interledger Payment pointer.

Considering the potential impact for the community vs the effort, 1 line of code (`<meta name="monetization" content="$your.payment.pointer.address/xxx">`), it will likely be useful to the community that we add the meta tag.

## Priority Assessment
This table checks this project against the [OWD prioritization criteria](https://github.com/openwebdocs/project/blob/main/steering-committee/prioritization-criteria.md).
Criteria | Assessment
------------ | -------------
Effort | __Minimal__. We only require to add a new meta to the parent HTML with the OWD payment point or the interledger payment pointer of Non-profits like Creative Commons, Contract for the Web, or the Web Foundation. See a list of [Non-profit payment pointers](https://community.webmonetization.org/grantfortheweb/non-profit-payment-pointers-2890).
Dependencies | None. Does not depend on or affect any other component
Community enablement | Has the potential to support other communities when we set the payment pointer as theirs. They receive micropayments daily. To make things interesting, the payment pointer can be rotated to the payment pointer of community contributors on a weekly/monthly basis. This will hopefully drive more engagement and provide additional incentives for contributors to continue contributing.
Momentum | Yes. There is work being done with Web Monetization by the [Grant for the Web Community](https://community.webmonetization.org/), the proposed new [Rafiki open-source tool](https://write.as/coil/introducing-rafiki-an-all-in-one-solution-for-interledger-wallets).
Enabling learners | We Monetized Learners, even those using Samsung Internet and Puma Mobile browsers will be able to support OWD
Enabling professionals | Professional Web Developers who create articles, tutorials, and learning series will be able to earn from their content when they learn about it from using MDN. This has the potential to increase the number of content they create to further enable more new Developers to learn from them.
Underrepresented topics / ethical web | The Web Monetization standard is privacy-focused on information about the user that is not collected or retained by the Web Monetization provider.
Operational necessities | NA
Addressing needs of the Web industry | Yes. There is a pressing need for more open, transparent, and fair payment for web content. Developers and other web content creators and maintainers put out useful content but they cannot earn from it from open-source web standard tools. The Web Monetization standard enables that for Web content creators and MDN is a place where many Developers start.

## Implementation Process
- [ ] Decide which Interledger payment pointer to use
  - [ ] Get a Payment pointer for OWD so OWD receives the payment
  - [ ] Use the payment pointer of a [Non-profit payment pointers](https://community.webmonetization.org/grantfortheweb/non-profit-payment-pointers-2890)
- [ ] Add the meta tag to the <head/> of the pages

## Resources
- [Web Monetization Spec](https://webmonetization.org/)
- [Web Monetized sites]()

**Comment by Elchi3** [comment]
We met last Wednesday (June 9th, 2021) to assess this project. Thanks for writing it down in such details!
Unfortunately, we can't really give an answer to this proposal. It would be better you discuss this idea with Mozilla and/or forums like the MDN Product Advisory Board.
